name: Step 0, Start

# This step triggers after the learner creates a new repository from the template
# This step sets STEP to 1
# This step closes <details id=0> and opens <details id=1>

# This will run every time we create push a commit to `main`

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  # Need `pull-requests: write` to create a pull request
  contents: write
  pull-requests: write

jobs:
  on_start:
    name: On start

    # We will only run this action when:
    # 1. This repository isn't the template repository
    if: ${{ !github.event.repository.is_template }}

    # We'll run Unbuntu for performance instead of Mac or Windowi
    runs-on: ubuntu-latest

    steps:
      # We 'll need to check out the repository so that we can edit the README'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      # Make a branch, file, commit, and pull request for the learner
      - name: Prepare a pull request, branch, and file
        run: |
          echo "Make sure we are on step 0"
          if [ "$(cat .github/script/STEP)" != 0]
          then
            echo "Current step is not 0"
            exit 0
          fi

          echo "Make a branch"
          BRANCH=welcome-workflow
          git checkout -b $BRANCH

          echo "Make a commit"
          git config user.name github-actions
          git config user.email github-action@github.com
          git commit --allow-empty --message="Create an empty commit"

          echo "Push"
          git push --set-upstream origin $BRANCH

          echo "Make a pull request"
          gh pr create --title "Post welcome comment workflow" --body "Post welcome comment workflow"

          echo "Restore main"
          git checkout main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      
      # Update README to close <details id=0> and open <details id=1>
      # and set STEP to '1'
      - name: Update to step 1
        uses: chanelcolgate/git-workflow-team@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          from_step: 0
          to_step: 1
          branch_name: welcome-workflow
