name: Lint
on: [push, pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: |
          npm install htmlhint -g

      - name: Lint with HTMLHint
        run: htmlhint publish-packages/index.html
