name: Lint
on: [push, pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - run: |
          npm ci
          npm run build --if-present
          npm test
          npm install htmlhint --save-dev

      - name: Lint with HTMLHint
        run: hmtlhint publish_packages/index.html
